name: 'Gource Action'
description: 'Creates a gource.io visualisation for a repo'
author: 'Sascha Mann'
branding:
  icon: 'film'
  color: 'blue'

inputs:
  gource-params:
    description: 'All parameters given to gource'
    default: ''
    required: false
  output-path:
    description: 'Path to write the video file to'
    default: 'out.mp4'
    required: false

runs:
  using: 'composite'
  steps:
    # Install gource
    - run: |
        sudo apt-get update -y
        sudo apt-get install -y gource
      shell: bash
    
    # Test installation
    - run: gource -h
      shell: bash
