name: 'Gource Action'
description: 'Creates a gource.io visualisation for a repo'
author: 'Sascha Mann'
branding:
  icon: 'film'
  color: 'blue'

inputs:
  gource-params:
    description: 'All parameters given to gource'
    default: ''
    required: false
  output-path:
    description: 'Path to write the video file to'
    default: 'out.mkv'
    required: false

runs:
  using: 'composite'
  steps:
    # Install gource
    - run: |
        sudo apt-get update -y
        sudo apt-get install -y gource ffmpeg 
      shell: bash
    
    # Test installation
    - run: xvfb-run -a -s "-screen 0 1280x720x24" gource --viewport 1280x720 -s 0.25 -r 60 --stop-at-end --multi-sampling --user-scale 1.25 --hide "filenames,mouse,usernames,dirnames" -o - | ffmpeg -y -b 10000K -r 60 -f image2pipe -vcodec ppm -i - -vcodec libx265 -b:v 10000K ${{ inputs.output-path }}
      shell: bash
